In [1]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
%matplotlib inline

In [5]:
bankdata = pd.read_csv("C:\\Users\\Ashu\\Downloads\\bill_authentication.csv")  

In [6]:
X = bankdata.drop('Class', axis=1)  
y = bankdata['Class']  

In [7]:
X.shape

(1372, 4)

In [8]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20) 

## Linear SVM:

In [11]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [12]:
y_pred = svclassifier.predict(X_test)  

In [13]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

[[157   3]
 [  0 115]]
             precision    recall  f1-score   support

          0       1.00      0.98      0.99       160
          1       0.97      1.00      0.99       115

avg / total       0.99      0.99      0.99       275



## Polynomial Kernel:

In [17]:
from sklearn.svm import SVC  
svclassifier_poly = SVC(kernel='poly', degree=2)  
svclassifier_poly.fit(X_train, y_train)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=2, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [18]:
y_pred = svclassifier_poly.predict(X_test) 

In [19]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred)) 

[[160   0]
 [  1 114]]
             precision    recall  f1-score   support

          0       0.99      1.00      1.00       160
          1       1.00      0.99      1.00       115

avg / total       1.00      1.00      1.00       275



## RBF Kernel

In [20]:
from sklearn.svm import SVC  
svclassifier_rbf = SVC(kernel='rbf')  
svclassifier_rbf.fit(X_train, y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [21]:
y_pred = svclassifier_rbf.predict(X_test)  

In [22]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred)) 

[[160   0]
 [  0 115]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       160
          1       1.00      1.00      1.00       115

avg / total       1.00      1.00      1.00       275



# Conclusion:
### Gaussian RBF Kernel are much better kernels as they are general purpose kernels.